# Generated by Django 3.0.7 on 2020-06-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.IntegerField()),
                ('ip', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('id', 'computer_id')},
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('build', models.CharField(max_length=50)),
                ('bits', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='Rams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(max_length=15)),
                ('hardware_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Computers')),
            ],
            options={
                'unique_together': {('id', 'hardware_id')},
            },
        ),
        migrations.CreateModel(
            name='Motherboards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
                ('hardware_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Computers')),
            ],
            options={
                'unique_together': {('id', 'hardware_id')},
            },
        ),
        migrations.CreateModel(
            name='Gpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(max_length=6)),
                ('hardware_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Computers')),
            ],
            options={
                'unique_together': {('id', 'hardware_id')},
            },
        ),
        migrations.CreateModel(
            name='Disks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(max_length=50)),
                ('hardware_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Computers')),
            ],
            options={
                'unique_together': {('id', 'hardware_id')},
            },
        ),
        migrations.CreateModel(
            name='Cpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('cores', models.IntegerField(max_length=4)),
                ('threads', models.IntegerField(max_length=5)),
                ('speed', models.IntegerField(max_length=5)),
                ('bits', models.IntegerField(max_length=8)),
                ('hardware_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Computers')),
            ],
            options={
                'unique_together': {('id', 'hardware_id')},
            },
        ),
    ]
