# Generated by Django 3.0.7 on 2020-06-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='computer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.Computers'),
        ),
        migrations.AddField(
            model_name='software',
            name='computer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.Computers'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gpus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='motherboards',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rams',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='os',
            unique_together={('id', 'computer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='software',
            unique_together={('id', 'computer_id')},
        ),
    ]
