# Generated by Django 3.0.7 on 2020-06-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200627_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpus',
            old_name='hardware_id',
            new_name='computer_id',
        ),
        migrations.RenameField(
            model_name='disks',
            old_name='hardware_id',
            new_name='computer_id',
        ),
        migrations.RenameField(
            model_name='gpus',
            old_name='hardware_id',
            new_name='computer_id',
        ),
        migrations.RenameField(
            model_name='motherboards',
            old_name='hardware_id',
            new_name='computer_id',
        ),
        migrations.RenameField(
            model_name='rams',
            old_name='hardware_id',
            new_name='computer_id',
        ),
        migrations.AlterUniqueTogether(
            name='cpus',
            unique_together={('id', 'computer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='disks',
            unique_together={('id', 'computer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='gpus',
            unique_together={('id', 'computer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='motherboards',
            unique_together={('id', 'computer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rams',
            unique_together={('id', 'computer_id')},
        ),
    ]
