# Generated by Django 3.0.7 on 2020-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200627_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='rams',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(max_length=250),
        ),
    ]
